project:
  type: website
  render:
    - "*.qmd"
    - "slides/*.qmd"
  preview:
    port: 3434
    browser: true
    watch-inputs: true
    timeout: 3600
lang: es
website:
  title: "DataVal-rladiesBA"
  page-navigation: true
  description: "Página principal del taller ... de RLadies Buenos Aires 2025."
  site-url: "https://mcnanton.github.io/DataVal-rladiesBA/"
  favicon: "images/logo-rladies-BA.png"
  repo-url: https://github.com/mcnanton/DataVal-rladiesBA
  repo-actions: [source, edit, issue]
  page-footer:
    left: "&copy; 2025 María Nanton, Betsabé Cohen"
    right: "Website construida con [Quarto](https://quarto.org/)."
    background: "#4c074d"
  sidebar:
    background: "#4c074d"
    logo: "images/logo-unificado.png"
    pinned: true
    align: center
    style: docked
    type: dark
    tools:
      - icon: github
        href: https://github.com/mcnanton/DataVal-rladiesBA
        text: GitHub
    contents:
     - href: index.qmd
       text: Inicio
     - href: setup.qmd
       text: Instrucciones de configuración
     - href: materiales.qmd
       text: Materiales
     - href: license.qmd
       text: Licencia
format:
  html:
    theme: [flatly, theme.scss]
    toc: true
    smooth-scroll: true
    link-external-newwindow: true
    code-link: true
    code-copy: true
    code-overflow: scroll
    mainfont: Atkinson Hyperlegible
    highlight-style: a11y
# lightbox extension
# https://github.com/quarto-ext/lightbox
lightbox:
  desc-position: right  # position of description
  # match: auto # give all images lightbox treatment
  effect: zoom # how lightbox opens/closes
  loop: false # doesn't loop to first image in gallery
0 commit comments
Comments
0
